Add missing date to resources.yaml
It is required to be in name and re-release of the same image should not
change it to keep the same name,

  File "pubtools-marketplacesvm/src/pubtools/_marketplacesvm/cloud_providers/aws.py", line 382, in _upload
    name = name_from_push_item(push_item, ami_version_template)
  File "pubtools-marketplacesvm/src/pubtools/_marketplacesvm/cloud_providers/aws.py", line 74, in name_from_push_item
    parts.append(release.date.strftime("%Y%m%d"))
  AttributeError: 'NoneType' object has no attribute 'strftime'

It was automatically extracted from koji metadata as build completion
date which is kind of equiivalent